name: Build

on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Set up Gradle (Windows uniquement)
        if: matrix.os == 'windows-latest'
        uses: gradle/gradle-build-action@v2

      - name: Build the app
        run: ./gradlew packageReleaseDistZip

      - name: Upload build artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/compose/binaries/main/release/

      - name: Upload build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/compose/binaries/main/release/
