name: Build

on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Build the app
        run: ./gradlew packageDmg

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: /Users/runner/work/AndroidTools/AndroidTools/composeApp/build/compose/binaries/main/dmg
