name: Build

on:
  push:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-13
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Build the app
        run: ./gradlew packageDmg

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: /Users/runner/work/AndroidTools/AndroidTools/composeApp/build/compose/binaries/main/dmg

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Build the app
        run: ./gradlew packageMsi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: D:\a\AndroidTools\AndroidTools\composeApp\build\compose\binaries\main\msi\fr.thomasbernard03.androidtools-1.0.0.msi
